version: "3"
services:
  postgres:
      ports:
        - '5436:5432'
      image: postgres:13.3
      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: always
        